service: aws-serverless-nodejs-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["UserTable", "Arn"] }

functions:
  hello:
    handler: src/handlers.helloWorld
    events:
      - httpApi:
          path: /hello
          method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
